### ISSUE TITLE
OusterImageConverter has different interfaces on the Rooster & master

### ISSUE THREAD

**Issue by dwisth** [ori-drs/lidar_undistortion#9]
@mcamurri - is it possible to standardise the interface for `OusterImageConverter` between `master` and `gen2-ouster-support` branches?

I currently need to modify vilens to run it on the Rooster because it is using the gen2 driver branch.

**Comment by mcamurri** [comment]
I was actually going to merge the gen2-ouster-support branch to master at some point but ICRA deadline you know...I'll do that soon.
